<?php if(Mage::getStoreConfig('multiproduct/block2/enable')) : ?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');    
    $newsaleicon = Mage::getStoreConfig('mygeneral/product_list/newsaleicon');    
    $displayaddtolink = Mage::getStoreConfig('mygeneral/product_list/display_comparewishlistlink');
    $display_productaddtocart = Mage::getStoreConfig('mygeneral/product_list/display_productaddtocart');
    $display_productname_singleline = Mage::getStoreConfig('mygeneral/product_list/display_productname_singleline');
    $ajaxcart = Mage::getStoreConfig('mygeneral/product_list/ajaxcart');
    $page_title = Mage::getStoreConfig('mygeneral/home/featured_product_title');
    $page_title = Mage::getStoreConfig('multiproduct/block2/block_title');
    if(!isset($page_title) || $page_title == "")
    {
	$page_title = $this->__('Bestsellers');
    }
?>
<?php $page = Mage::app()->getLayout()->getBlock('root')->getTemplate();	    
    if ($page == "page/1column.phtml") {
	$page = 1;
    }
    elseif ($page == "page/2columns-left.phtml" || $page == "page/2columns-right.phtml") {
	$page = 2;
    }
    elseif($page == "page/3columns.phtml") {
	$page = 3;		
    }
    else {
	$page = 0;
    }		
?>
<?php if($_productCollection->count()): ?>
<?php $_collectionSize = $_productCollection->count() ?>
    <div class="clearer martop50">&nbsp;</div>
    <div class="page-title section-title">
	<h2><?php echo $page_title; ?></h2>
    </div>
	<div id="bestsellers" class="products-grid itemslider">
	<?php $i=0;$j=0; foreach ($_productCollection as $_product): ?>
	
	    <div class="item">
		
		<div class="product-image-wrapper">
			    
		    
		    <?php if($newsaleicon == '1') { ?> 
			<?php $adate = date('Y-m-d');  //echo 'frpm:-'.$_product->special_from_date.'----';echo "to:-".$_product->special_to_date.'--';
				$a= 0;
				if($_product->special_from_date != null && $_product->special_to_date == "")
				{
				    if( $adate >= $_product->special_from_date)
				    {
					    $a = 1; 
				    }
				}
				if($_product->special_from_date != "" && $_product->special_to_date != "")
				{
				    if($adate >= $_product->special_from_date && $adate <= $_product->special_to_date)
				    {
				    $a = 1; 
				    }
				}
				    
				    if($a == 1){ ?>
				   <div class="sale"><label><?php echo $this->__('PROMO') ?></label></div>
				    <?php } ?>
				
				
			      <?php $bdate = date('Y-m-d');
				$b= 0;
				if($_product->news_from_date != null && $_product->news_to_date == "")
				{
				    if( $bdate >= $_product->news_from_date)
				    {
					    $b = 1; 
				    }
				}
				if($_product->news_from_date != "" && $_product->news_to_date != "")
				{
				    if($bdate >= $_product->news_from_date && $bdate <= $_product->news_to_date)
				    {
				    $b = 1; 
				    }
				}
				    if($b == 1){ ?>
				   <div class="new"><label><?php echo $this->__('NEW IN') ?></label></div>
				    <?php } 
				?>  
		    <?php } ?>
		    
		    <?php
			$class = "";
			$alterImage = Mage::helper("ExtraConfig")->getAltImgHtml($_product, 280, 280,'thumbnail');
			if($alterImage != false)
			{
				 $class = 'class="small-image"';
			}
		    ?>
		    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
			<img <?php echo $class;?> src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280) ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			<?php  echo $alterImage; ?>
		    </a>		    		    
		    
		    <div class="quick-view">
			<?php if($ajaxcart == '2') { ?>
			<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>'><span><?php echo $this->__('Espiadinha') ?></span></a>
			<?php } ?>
		    </div>
		    
		    <div id='ajax_loader-best<?php echo $_product->getId()?>' class="ajaxcartpro_progress" style="display: none;"></div>							    
		    
		</div>
		
		<?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productname',0) != 'off'
		    ||  Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productprice',0) != 'off'
		    ||	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productratings',0) != 'off'
		    ||	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productaddtocart',0) != 'off'
		    ||	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_wishlistlink',0) != 'off'
		    || 	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_comparelink',0) != 'off'
		):?>
		    <div class="product-content-wrapper">
			<div class="divider"></div>
		<?php endif; ?>
		
		    
		    <?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productname',0) != 'off'):?>
			<h3 class="product-name<?php if($display_productname_singleline == '1'){ ?> single-line-name<?php } ?> <?php echo Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productname',0);?>"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->htmlEscape($_product->getName()); ?></a></h3>
		    <?php endif; ?>
		    
		    <?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productprice',0) != 'off') :?>
			<div class="<?php echo Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productprice',0);?>">
			    <?php echo $this->getPriceHtml($_product, true) ?>			    
			</div>
		    <?php endif;?>
		    
		    
		    <?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productratings',0) != 'off') :?>
			<div class="<?php echo Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productratings',0);?>">
			    <?php echo $this->getReviewsSummaryHtml($_product, 0, true); ?>			
			</div>
		    <?php endif;?>
				
					    
		    
		    <?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productaddtocart',0) != 'off') { ?>
		    <div class="btn-cart  <?php echo Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productaddtocart',0);?>">
			<?php if($_product->isSaleable()): ?>
			    <?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
				<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
				    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajx-cart" onclick="setLocationAjax1('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo '-best'.$_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
				<?php } else { ?>
				    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
				    <a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'></a>
				<?php }  ?>			    
			    <?php } else { ?>
				<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
			    <?php } ?>
			<?php else: ?>
			    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
			<?php endif; ?>
		    </div>
		    <?php } ?>
		    
		    
		    <?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_wishlistlink',0) != 'off' || Mage::helper("ExtraConfig")->hoverCssAvaibility('display_comparelink',0) != 'off') { ?>
		        <ul class="add-to-links">
		    <?php } ?>
			<?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_wishlistlink',0) != 'off') { ?>
			    <li class="first  <?php echo Mage::helper("ExtraConfig")->hoverCssAvaibility('display_wishlistlink',0);?>">
				<?php if ($this->helper('wishlist')->isAllow()) : ?>
				    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><span class="icon fa fa-heart-o"></span><?php echo $this->__('Add to Wishlist') ?></a>
				<?php endif; ?>
			    </li>
			<?php } ?>
			<?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_comparelink',0) != 'off') { ?>
			    <li class="last  <?php echo Mage::helper("ExtraConfig")->hoverCssAvaibility('display_comparelink',0);?>">
			    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
				<a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><span class="icon fa fa-copy"></span><?php echo $this->__('Add to Compare') ?></a>
			    <?php endif; ?>
			    </li>
			<?php } ?>
		    <?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_wishlistlink',0) != 'off' || Mage::helper("ExtraConfig")->hoverCssAvaibility('display_comparelink',0) != 'off') { ?>
		        </ul>
		    <?php } ?>

	    	<?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productname',0) != 'off'
		    ||  Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productprice',0) != 'off'
		    ||	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productratings',0) != 'off'
		    ||	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productaddtocart',0) != 'off'
		    ||	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_wishlistlink',0) != 'off'
		    || 	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_comparelink',0) != 'off'
		):?>
		    </div>
		<?php endif; ?>   		    		    
		
	    </div>
	<?php endforeach ?>
	</div>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>	    

<script>
j$(document).ready(function() {
j$("#bestsellers").owlCarousel({
    itemsCustom : [
	<?php if ($page == 1) : ?>
	    [0, 1],
	    [380, 2],
	    [625, 3],
	    [1265, 4],
	    [1360, 4],
	    [1440, 4],
	    [1680, 4]
	<?php elseif ($page == 2) : ?>
	    [0, 1],
	    [380, 2],
	    [625, 3],
	    [1265, 3],
	    [1360, 3],
	    [1440, 3],
	    [1680, 3]
	<?php elseif ($page == 3) : ?>
	    [0, 1],
	    [380, 2],
	    [625, 3],
	    [753, 2],
	    [1265, 2],
	    [1360, 2],
	    [1440, 2],
	    [1680, 2]
	<?php endif; ?>
    ]<?php  echo Mage::helper("ExtraConfig")->sliderSetting(); ?>
});
});
</script>

<?php endif; ?>
<?php endif; ?>