
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');    
    $newsaleicon = Mage::getStoreConfig('mygeneral/product_list/newsaleicon');
     $alterImage = Mage::getStoreConfig('mygeneral/product_list/enable_alter'); 
    $displayaddtolink = Mage::getStoreConfig('mygeneral/product_list/display_comparewishlistlink');
    $display_productaddtocart = Mage::getStoreConfig('mygeneral/product_list/display_productaddtocart');
    $display_productname_singleline = Mage::getStoreConfig('mygeneral/product_list/display_productname_singleline');
    $ajaxcart = Mage::getStoreConfig('mygeneral/product_list/ajaxcart');
       
    if($_GET['layout']) {
	$page = $_GET['layout'];
    }
    else {
	$page = Mage::app()->getLayout()->getBlock('root')->getTemplate();
	if ($page == "page/1column.phtml") {
	    $page = 1;
	}
	elseif ($page == "page/2columns-left.phtml" || $page == "page/2columns-right.phtml") {
	    $page = 2;
	}	
	elseif($page == "page/3columns.phtml") {
	    $page = 3;		
	}
	else {
	    $page = 0;
	}
    }
    
    $blockId = "";
    if($this->getCustomBlockId()) {
	$blockId = "-".$this->getCustomBlockId();
    }
?>
<?php if($_productCollection->count()): ?>
<?php $_collectionSize = $_productCollection->count() ?>    	
	<?php $i=0;$j=0; foreach ($_productCollection as $_product): ?>
	
	    <li class="item">
		
		<div class="product-image-wrapper">			    
		    
		    <?php if($newsaleicon == '1') { ?> 
			<?php $adate = date('Y-m-d');  //echo 'frpm:-'.$_product->special_from_date.'----';echo "to:-".$_product->special_to_date.'--';
				$a= 0;
				if($_product->special_from_date != null && $_product->special_to_date == "")
				{
				    if( $adate >= $_product->special_from_date)
				    {
					    $a = 1; 
				    }
				}
				if($_product->special_from_date != "" && $_product->special_to_date != "")
				{
				    if($adate >= $_product->special_from_date && $adate <= $_product->special_to_date)
				    {
				    $a = 1; 
				    }
				}
				    
				    if($a == 1){ ?>
				   <div class="sale"><label><?php echo $this->__('PROMO') ?></label></div>
				    <?php } ?>
				
				
			      <?php $bdate = date('Y-m-d');
				$b= 0;
				if($_product->news_from_date != null && $_product->news_to_date == "")
				{
				    if( $bdate >= $_product->news_from_date)
				    {
					    $b = 1; 
				    }
				}
				if($_product->news_from_date != "" && $_product->news_to_date != "")
				{
				    if($bdate >= $_product->news_from_date && $bdate <= $_product->news_to_date)
				    {
				    $b = 1; 
				    }
				}
				    if($b == 1){ ?>
				   <div class="new"><label><?php echo $this->__('NEW IN') ?></label></div>
				    <?php } 
				?>  
		    <?php } ?>
		    
		    <?php if($alterImage == '1') { ?>
			<div id="product-<?php echo$_product->getId();?>">
			    <div class="multi-image">
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
				<?php $defaultSelectedImage = basename($this->helper('catalog/image')->init($_product, 'small_image')->resize(280));?>
				    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
				</a>
			    </div>
			<?php
			    $_galleryImages = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
			     foreach($_galleryImages as $_proImage) {
				$gallerySelectedImage = basename($this->helper('catalog/image')->init($_product, 'small_image',$_proImage->getFile())->resize(280));
				if($defaultSelectedImage != $gallerySelectedImage){
			?>
			    <div class="multi-image">
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
				    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image',$_proImage->getFile())->resize(280); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
				</a>
			    </div>
			<?php }} ?>
			</div>
			<script>
			    j$(document).ready(function() {
			    j$("#product-<?php echo$_product->getId();?>").owlCarousel({
				itemsCustom : [
					[0, 1]
				]<?php  echo Mage::helper("ExtraConfig")->sliderSetting();?>
				});
			    });
			</script>
		    <?php } else { ?>
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
			    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280) ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			</a>
		    <?php } ?>
		    
		    <div class="quick-view">
			<?php if($ajaxcart == '2') { ?>
			<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>'><span><?php echo $this->__('Espiadinha') ?></span></a>
			<?php } ?>
		    </div>
		    
		    <div id='ajax_loader<?php echo $_product->getId()?>' class="ajaxcartpro_progress" style="display: none;"></div>					    
		    
		</div>
		
		<?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productname') != 'off'
		    ||  Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productprice') != 'off'
		    ||	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productratings') != 'off'
		    ||	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productaddtocart') != 'off'
		    ||	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_wishlistlink') != 'off'
		    || 	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_comparelink') != 'off'
		):?>
		    <div class="product-content-wrapper">
			<div class="divider"></div>
		<?php endif; ?>
		
		    
		    
		    <?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productname') != 'off'):?>
			<h3 class="product-name<?php if($display_productname_singleline == '1'){ ?> single-line-name<?php } ?> <?php echo Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productname');?>"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->htmlEscape($_product->getName()); ?></a></h3>
		    <?php endif; ?>
		    
		    <?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productprice') != 'off') :?>
			<div class="<?php echo Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productprice');?>">
			    <?php echo $this->getPriceHtml($_product, true) ?>			    
			</div>
		    <?php endif;?>
		    
		    
		    <?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productratings') != 'off') :?>
			<div class="<?php echo Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productratings');?>">
			    <?php echo $this->getReviewsSummaryHtml($_product, false, true); ?>			
			</div>
		    <?php endif;?>
				
					    
		    
		    <?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productaddtocart') != 'off') { ?>
		    <div class="btn-cart  <?php echo Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productaddtocart');?>">
			<?php if($_product->isSaleable()): ?>
			    <?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
				<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
				    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajx-cart" onclick="setLocationAjax1('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
				<?php } else { ?>
				    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
				    <a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'></a>
				<?php }  ?>			    
			    <?php } else { ?>
				<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
			    <?php } ?>
			<?php else: ?>
			    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
			<?php endif; ?>
		    </div>
		    <?php } ?>
		    
		    
		    <?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_wishlistlink') != 'off' || Mage::helper("ExtraConfig")->hoverCssAvaibility('display_comparelink') != 'off') { ?>
		        <ul class="add-to-links">
		    <?php } ?>
			<?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_wishlistlink') != 'off') { ?>
			    <li class="first  <?php echo Mage::helper("ExtraConfig")->hoverCssAvaibility('display_wishlistlink');?>">
				<?php if ($this->helper('wishlist')->isAllow()) : ?>
				    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><span class="icon fa fa-heart-o"></span><?php echo $this->__('Add to Wishlist') ?></a>
				<?php endif; ?>
			    </li>
			<?php } ?>
			<?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_comparelink') != 'off') { ?>
			    <li class="last  <?php echo Mage::helper("ExtraConfig")->hoverCssAvaibility('display_comparelink');?>">
			    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
				<a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><span class="icon fa fa-copy"></span><?php echo $this->__('Add to Compare') ?></a>
			    <?php endif; ?>
			    </li>
			<?php } ?>
		    <?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_wishlistlink') != 'off' || Mage::helper("ExtraConfig")->hoverCssAvaibility('display_comparelink') != 'off') { ?>
		        </ul>
		    <?php } ?>

	    	<?php if(Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productname') != 'off'
		    ||  Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productprice') != 'off'
		    ||	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productratings') != 'off'
		    ||	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_productaddtocart') != 'off'
		    ||	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_wishlistlink') != 'off'
		    || 	Mage::helper("ExtraConfig")->hoverCssAvaibility('display_comparelink') != 'off'
		):?>
		    </div>
		<?php endif; ?>
	    </li>    
	<?php endforeach ?>
<?php endif; ?>