/*
Do not change this file it lost your changes.
*/

<?php
$instance = Mage::helper("ExtraConfig");
$store = Mage::app()->getRequest()->getParam('store');
$responsive = Mage::getStoreConfig('themelayout/layout/responsiveness',$store);
$width = Mage::getStoreConfig('themelayout/layout/layout_width',$store);
$customwidth = Mage::getStoreConfig('themelayout/layout/custom_width',$store);
$fluidwidth = Mage::getStoreConfig('themelayout/layout/fluid_width',$store);
$responsivewidth = $instance->responsivewidth();
$maxwidth = $instance->maxwidth($store);
$maxbreak = $instance->breakpoint($maxwidth, $store);
?>


/* Grid container
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/
    <?php if($responsive){ ?>
	.container {
		width:96%;
                <?php if ($maxbreak == 960){ ?>
			<?php if ($width == 'custom'){ ?>
				max-width: <?php echo $customwidth; ?>px;
			<?php } else { ?>
				max-width: <?php echo $responsivewidth['960']; ?>px;
			<?php } ?>    
		<?php } else { ?>
                        <?php if (!$fluidwidth){ ?>
		    	max-width: <?php echo $responsivewidth['960']; ?>px;
                        <?php } ?>
		<?php } ?>	
        }
        <?php if ($width == 'custom'){ ?>
		.lte-ie8 .container { max-width:<?php echo $customwidth; ?>px; }
	<?php } else { ?>
		.lte-ie8 .container { max-width:<?php echo $responsivewidth[$width]; ?>px; }
	<?php } ?>
        
    <?php } else { ?>
    
        <?php 
		$nonresponsivewidth = 0;
		if ($width == 'custom') {
                    $nonresponsivewidth = $customwidth;
		} else {
                    $nonresponsivewidth = $responsivewidth[$width];
                }
	?>
	.container {
		width: <?php echo $nonresponsivewidth; ?>px !important;
	}
    <?php } ?>
        
        
        
<?php if($responsive){ ?>


<?php if($maxbreak >= 1920) { ?>


/* Desktop - design for a width of 1920px
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/

/* 1680px <= width */

@media only screen and (min-width: 1920px) {
        <?php if($maxbreak == 1920){ ?>
            <?php if($width == 'custom') { ?>
                .container { max-width:<?php echo $customwidth; ?>px; }
            <?php } else { ?>
                .container { max-width:<?php echo $responsivewidth['1920']; ?>px; }
            <?php } ?>
	<?php } else { ?>
            <?php if (!$fluidwidth){ ?>
                .container { max-width:<?php echo $responsivewidth['1920']; ?>px; }
            <?php } ?>
        <?php } ?>

	/* Special grid units */
	.grid-col2-sidebar	{ width: 16.11%; }
	.grid-col2-main		{ width: 79.88%; }
	.grid-col3-sidebar		{ width:20.18%; }
	.grid-col3-main			{ width:77.34%; }
	
	/* Hide */
	.hide-below-1680 { display:inherit !important; }
	.hide-below-1440 { display:inherit !important; }
	.hide-below-1360 { display:inherit !important; }
	.hide-below-1280 { display:inherit !important; }
}
<?php } ?>






<?php if($maxbreak >= 1680) { ?>


/* Desktop - design for a width of 1680px
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/

/* 1680px <= width */

@media only screen and (min-width: 1680px) <?php if($maxbreak > 1680){ ?>and (max-width: 1919px)<?php } ?> {
        <?php if($maxbreak == 1680){ ?>
            <?php if($width == 'custom') { ?>
                .container { max-width:<?php echo $customwidth; ?>px; }
            <?php } else { ?>
                .container { max-width:<?php echo $responsivewidth['1680']; ?>px; }
            <?php } ?>
	<?php } else { ?>
            <?php if (!$fluidwidth){ ?>
                .container { max-width:<?php echo $responsivewidth['1680']; ?>px; }
            <?php } ?>
        <?php } ?>

	/* Special grid units */
	.grid-col2-sidebar	{ width: 16.11%; }
	.grid-col2-main		{ width: 79.88%; }
	.grid-col3-sidebar		{ width:20.18%; }
	.grid-col3-main			{ width:77.34%; }
	
	/* Hide */
	.hide-below-1680 { display:inherit !important; }
	.hide-below-1440 { display:inherit !important; }
	.hide-below-1360 { display:inherit !important; }
	.hide-below-1280 { display:inherit !important; }
}
<?php } ?>


<?php if($maxbreak >= 1440) { ?>
/* Desktop - design for a width of 1440px
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/

/* 1440px <= width */

@media only screen and (min-width: 1440px) <?php if($maxbreak > 1440){ ?>and (max-width: 1679px)<?php } ?> {

	<?php if($maxbreak == 1440){ ?>
            <?php if($width == 'custom') { ?>
                .container { max-width:<?php echo $customwidth; ?>px; }
            <?php } else { ?>
                .container { max-width:<?php echo $responsivewidth['1440']; ?>px; }
            <?php } ?>
        <?php } else { ?>
            <?php if (!$fluidwidth){ ?>
                .container { max-width:<?php echo $responsivewidth['1440']; ?>px; }
            <?php } ?>
        <?php } ?>
	
				
	/* Special grid units */
	.grid-col2-sidebar 	{ width: 17.75%; }
	.grid-col2-main		{ width: 78.24%; }
	.grid-col3-sidebar		{ width:22.68%; }
	.grid-col3-main			{ width:74.90%; }
	
	/* Hide */
	.hide-below-1440 { display:inherit !important; }
	.hide-below-1360 { display:inherit !important; }
	.hide-below-1280 { display:inherit !important; }
}
<?php } ?>



<?php if($maxbreak >= 1360 ) { ?>
/* Desktop - design for a width of 1366px and 1360px
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/

/* 1360px <= width */

@media only screen and (min-width: 1360px) <?php if($maxbreak > 1360){ ?>and (max-width: 1439px)<?php } ?> {

	<?php if($maxbreak == 1360){ ?>
            <?php if($width == 'custom') { ?>
                .container { max-width:<?php echo $customwidth; ?>px; }
            <?php } else { ?>
                .container { max-width:<?php echo $responsivewidth['1360']; ?>px; }
            <?php } ?>
        <?php } else { ?>
            <?php if (!$fluidwidth){ ?>
                .container { max-width:<?php echo $responsivewidth['1360']; ?>px; }
            <?php } ?>
        <?php } ?>
	
				
	/* Special grid units */
	.grid-col2-sidebar 	{ width: 18.84%; }
	.grid-col2-main 	{ width: 77.15%; }
	.grid-col3-sidebar		{ width:24.42%; }
	.grid-col3-main			{ width:72.98%; }
	
	/* Hide */
	.hide-below-1360 { display:inherit !important; }
	.hide-below-1280 { display:inherit !important; }
}
<?php } ?>



<?php if($maxbreak >= 1280) { ?>
/* Desktop - design for a width of 1280px
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/

/* 1280px <= width */

@media only screen and (min-width: 1280px) <?php if($maxbreak > 1280){ ?>and (max-width: 1359px)<?php } ?> {

	<?php if($maxbreak == 1280){ ?>
            <?php if($width == 'custom') { ?>
                .container { max-width:<?php echo $customwidth; ?>px; }
            <?php } else { ?>
                .container { max-width:<?php echo $responsivewidth['1280']; ?>px; }
            <?php } ?>
	<?php } else { ?>
            <?php if (!$fluidwidth){ ?>
                .container { max-width:<?php echo $responsivewidth['1280']; ?>px; }
            <?php } ?>
        <?php } ?>
				
	}
	/* Special grid units */
	.grid-col2-sidebar 	{ width: 21.87%; }
	.grid-col2-main		{ width: 74.13%; }
	.grid-col3-sidebar		{ width:29.50%; }
	.grid-col3-main			{ width:68.50%; }
	
	/* Hide */
	.hide-below-1280 { display:inherit !important; }
}
<?php } ?>




/* Design for a width of less than 1024 px
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/

/* width < 1024px */
@media only screen and (max-width: 1023px) {

	/* Hide */
	.hide-below-1024 { display:none !important; }
}


/* Tablet (Portrait) - design for a width of 768px
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/

/* 768px <= width < 960px */
@media only screen and (min-width: 768px) and (max-width: 959px) {
        <?php if (!$fluidwidth){ ?>
            .container { max-width:737px; }
        <?php } ?>
		
	/* Hide */
	.hide-below-960 { display:none !important; }
}


/* All mobile - design for a width of less than 768px
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/

/* width < 768px */
@media only screen and (max-width: 767px) {
	
	/* Grid units below 768px screen size are 100% wide with no margin. Padding compensates lack of margin. */
	.container { width:92%; padding-left:2%; padding-right:2%; }
	.nested-container { width:100%; margin-left:auto; }

	/* Nav container with outline (if nav container has background color).
	   Apply the same vertical margins, as container's side padding. */
	.nav.has-outline > .grid-full { margin-top: 2%; margin-bottom: 2%; }
	
	/* Below 768px all grid units are stretched (full width) and stack vertically */
	.grid12-1,
	.grid12-2,
	.grid12-3,
	.grid12-4,
	.grid12-5,
	.grid12-6,
	.grid12-7,
	.grid12-8,
	.grid12-9,
	.grid12-10,
	.grid12-11,
	.grid12-12,
	.grid-full,
	
	.grid-col2-sidebar,
	.grid-col2-main,
	.grid-col3-sidebar,
	.grid-col3-main
	{
		width:100% !important; /* Added "!important" to override units with "no-gutter" */
		margin-left:0;
		margin-right:0;
	}

	/* Vertically aligned grid
	-------------------------------------------------------------- */
	.v-grid-container { display:block; }
	.v-grid { float:inherit; display:block; width:100%; }
}


/* Mobile (Landscape) - design for a width of 480px
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/

/* 480px <= width < 768px */
@media only screen and (min-width: 480px) and (max-width: 767px) {
        <?php if (!$fluidwidth){ ?>
            .container { max-width:440px; }
        <?php } ?>
		
	/* Hide */
	.hide-below-960 { display:none !important; }
	.hide-below-768 { display:none !important; }
	
	/* Deprecated: persistent grid units (will be removed in the next update)
	-------------------------------------------------------------- */
		/* Half */
		.persistent-grid2-1 { width:48%; margin-left:1%; margin-right:1%; }
		
		/* One-third + two-thirds */
		.persistent-grid3-1 { width:31.33%; margin-left:1%; margin-right:1%; }
		.persistent-grid3-2 { width:64.67%; margin-left:1%; margin-right:1%; }
		
		/* One-fourth + two-fourths + three-fourths */
		.persistent-grid4-1 { width:23%; margin-left:1%; margin-right:1%; }
		.persistent-grid4-2 { width:48%; margin-left:1%; margin-right:1%; }
		.persistent-grid4-3 { width:73%; margin-left:1%; margin-right:1%; }

	/* Mobile grid (for browser viewport between 480px and 768px):
	   Below 768px all grid units are stretched (full width) and stack vertically.
	   The "mobile-grid" class forces narrow grid units to stay narrow,
	   but the width is increased to avoid too small columns.
	-------------------------------------------------------------- */
	.mobile-grid.grid12-1 { width:14.66% !important;	margin-left:1%; margin-right:1%; } /* 1/12 turns into 1/6 */
	.mobile-grid.grid12-2 { width:31.33% !important;	margin-left:1%; margin-right:1%; } /* 1/6  turns into 1/3 */
	.mobile-grid.grid12-3 { width:48% !important;		margin-left:1%; margin-right:1%; } /* 1/4  turns into 1/2 */
	
	/* Force other grid units to take half of the available width */
	.mobile-grid-half { width:48% !important; margin-left:1%; margin-right:1%; }

}


/* Mobile (Landscape, iPhone 4 Portrait) - design for a width of 640px
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/
/* 640px <= width < 768px */
@media only screen and (min-width: 640px) and (max-width: 767px) {
        <?php if (!$fluidwidth){ ?>
            .container { max-width:590px; }
        <?php } ?>
        
}


/* Design for a width of less than 480px (small mobile)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/

/* width < 480px */
@media only screen and (max-width: 479px) {

	/* Stretch containers to full width and add side padding */
	.container { max-width:none !important; width:94%; padding-left:3%; padding-right:3%; }

}


/* Mobile (Portrait) - design for a width of 320px
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/

/* 320px <= width < 480px */
@media only screen and (min-width: 320px) and (max-width: 479px) {
            <?php if (!$fluidwidth){ ?>
		/* .container { max-width:301px; } */
	    <?php } ?>
	/* Hide */
	.hide-below-960 { display:none !important; }
	.hide-below-768 { display:none !important; }
	.hide-below-480 { display:none !important; }
}


/* Mobile (Portrait) - design for a width of less than 320px
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
*/

/* width < 320px */
@media only screen and (max-width: 319px) {
            <?php if (!$fluidwidth){ ?>
		/* .container { max-width:226px; } */
            <?php } ?>
	.container { max-width:none !important; width:92%; padding-left:4%; padding-right:4%; }


	/* Hide */
	.hide-below-960 { display:none !important; }
	.hide-below-768 { display:none !important; }
	.hide-below-480 { display:none !important; }
	.hide-below-320 { display:none !important; }
}


<?php } ?>